#! /bin/bash

# Copy and paste this into an executable shell script on the hub.
## Check out the stsci-announce repo for live work in
## a JupyterHub notebook session.

set -eux

if [[ $# != 1 ]]; then
    echo "usage: $0  <branch-to-checkout>"
    exit 1
else
    BRANCH=$1
fi

git clone https://github.com/jaytmiller/stsci-announce.git

cd stsci-announce
git fetch origin
git checkout ${BRANCH}

source ~/.bashrc
conda activate base

# Partial install may fail,  but enables jlpm for below
set +e
pip install .
set -e

jlpm run clean
jlpm run build
jlpm install

pip install -ve .
jupyter labextension develop . --overwrite

# Will "update" to broken dependencies?
# jlpm  add @jupyterlab/application @lumino/widgets @jupyterlab/statusbar @jupyterlab/apputils @jupyterlab/settingregistry

jlpm run build
# jupyter labextension install .
